name: Gerar listas

on:
  create:
  "workflow_dispatch":
  push:
  schedule:
    - cron: "30 2 * * 2-5"

jobs:
  gerar-listas:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Checkout
        run: |
          git config user.name "Glauber Lima [GitHub Actions]"
          git config user.email "glauberlima@users.noreply.github.com"

      - name: Obter dados do Procon e gerar listas
        working-directory: ./lists
        run: |
          curl -s "https://sistemas.procon.sp.gov.br/evitesite/list/evitesite.php?action=list&jtStartIndex=0&jtPageSize=600&jtSorting=strSite%20ASC&_=$(date +%s)" | jq .Records[] | jq -r .strSite > raw.txt
          h=($(sha256sum raw.txt)); echo $h > .control; rm raw.txt
          git add .control
          if [ -z "$(git status --porcelain)" ]; then
              echo "Nenhuma alteração detectada."
              exit 0
          fi
          
          {
              echo "! Title: Evite esses Sites - Procon-SP"
              echo "! Expires: 1 day"
              echo "! Description: Lista gerada a partir do site Evite esses Sites - https://sistemas.procon.sp.gov.br/evitesite/list/evitesites.php - Fundação Procon/SP"
              echo "! Homepage: https://github.com/glauberlima/procon-badsites"
              echo "! Licence: https://github.com/glauberlima/procon-badsites/blob/main/LICENSE"
              echo "! Updated: $(date +"%d %B %Y %H:%M:%S (GMT%:z)")"
          } > adblock.txt
          while IFS= read -r line; do echo "||$line^" >> adblock.txt; done < raw.txt
          git add adblock.txt

          {
              echo "# Title: Evite esses Sites - Procon-SP"
              echo "# Description: Lista gerada a partir do site Evite esses Sites - https://sistemas.procon.sp.gov.br/evitesite/list/evitesites.php - Fundação Procon/SP"
              echo "# Homepage: https://github.com/glauberlima/procon-badsites"
              echo "# Licence: https://github.com/glauberlima/procon-badsites/blob/main/LICENSE"
              echo "# Updated: $(date +"%d %B %Y %H:%M:%S (GMT%:z)")"
          } > hosts.txt
          while IFS= read -r line; do echo "0.0.0.0 $line" >> hosts.txt; done < raw.txt
          git add hosts.txt

          git commit -m "Lista atualizada - $(date +"%d/%m/%Y %H:%M:%S (GMT%:z)")"
          git push
